In [2]:
!pip list | grep numpy

numpy               1.21.2


In [5]:
import numpy as np

In [8]:
a =np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
b = np.array([[4],
             [-1],
             [6]])
b

array([[ 4],
       [-1],
       [ 6]])

In [13]:
C = np.array([[3, -2],
                      [7,1]])
C

array([[ 3, -2],
       [ 7,  1]])

In [15]:
D = np.array([[3, -2, 0, 1],
                    [7, 1, -1, 2],
                    [4, -5, 1, 3]])
D

array([[ 3, -2,  0,  1],
       [ 7,  1, -1,  2],
       [ 4, -5,  1,  3]])

In [25]:
a= np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [30]:
a= np.array([2,3,4])
a

array([2, 3, 4])

In [32]:
B = np.array([[1.2, 3.5, 5.1], [-0.3, 1.1, -4.5]])
B

array([[ 1.2,  3.5,  5.1],
       [-0.3,  1.1, -4.5]])

In [41]:
a.shape # 

(2, 3)

In [36]:
a.ndim # 次元

1

In [42]:
a.dtype # データ型

dtype('int64')

In [43]:
B.shape

(2, 3)

In [45]:
B.ndim

2

In [47]:
B.dtype

dtype('float64')

In [50]:
a=np.arange(1,13,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [66]:
B = np.array([[2, 4, 6,], [-1, 5, -3], [0, -2, 3]])
B

array([[ 2,  4,  6],
       [-1,  5, -3],
       [ 0, -2,  3]])

In [60]:
a[2:]

array([ 5,  7,  9, 11])

In [61]:
a[::-1]

array([11,  9,  7,  5,  3,  1])

In [62]:
B

array([[ 2,  4,  6],
       [-1,  5, -3],
       [-1, -2,  3]])

In [63]:
B[0]

array([2, 4, 6])

In [67]:
B[2,0]

0

In [71]:
B[1:, 1:-1]

array([[ 5],
       [-2]])

In [73]:
a = np.array([[1,3], [-2,4]])
b = np.array([[2,-1], [3, 0]])
a+b

array([[3, 2],
       [1, 4]])

In [75]:
a = np.array([[1,3], [-2,4]])
b = np.array([[2,-1], [3, 0]])
a-b

array([[-1,  4],
       [-5,  4]])

In [77]:
a = np.array([[1,3], [-2,4]])
b = np.array([[2,-1], [3, 0]])
a @ b

array([[11, -1],
       [ 8,  2]])

In [79]:
a = np.array([[1,3], [-2,4]])
b = np.array([[2,-1], [3, 0]])
a.dot(b)

array([[11, -1],
       [ 8,  2]])

In [81]:
# アドマール積
a = np.array([[1,3], [-2,4]])
b = np.array([[2,-1], [3, 0]])
a*b

array([[ 2, -3],
       [-6,  0]])

In [82]:
a=np.array([[2,3,4]])
B =np.array([[1,3,4], [-3,1,4]])

In [84]:
a

array([[2, 3, 4]])

In [86]:
a.shape

(1, 3)

In [88]:
a.T

array([[2],
       [3],
       [4]])

In [90]:
a.T.shape

(3, 1)

In [92]:
B.T

array([[ 1, -3],
       [ 3,  1],
       [ 4,  4]])

In [97]:
A =np.array([[4,-2], [1, 0]])
A

array([[ 4, -2],
       [ 1,  0]])

In [99]:
det = np.linalg.det(A)
det==0.0

False

In [101]:
Ainv = np.linalg.inv(A) # 逆行列を求める
# 逆行列は元の行列とかけると単位行列（１）となる

In [103]:
Ainv @ A

array([[1., 0.],
       [0., 1.]])

In [105]:
# ブロードキャスト
# スカラ：ベクトルでも行列でもない数字

A =np.array([[4,-2], [1,0]])
A

array([[ 4, -2],
       [ 1,  0]])

In [108]:
B = np.array([[8,1,5], [-3, 0, -7]])
B

array([[ 8,  1,  5],
       [-3,  0, -7]])

In [110]:
A * 0.5

array([[ 2. , -1. ],
       [ 0.5,  0. ]])

In [113]:
B * 2

array([[ 16,   2,  10],
       [ -6,   0, -14]])

In [115]:
d = np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [117]:
d.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
B = np.array([[2,4,6], [-1,5,9], [0,5,3]])

In [120]:
B.max()

9

In [122]:
B.min(axis=1) # 列ごとに最小値を求めている

array([ 2, -1,  0])

In [124]:
B.sum(1)

array([12, 13,  8])

In [126]:
B.mean() #平均値

3.6666666666666665

In [128]:
B.var() #分散

8.444444444444445

In [131]:
B.std(axis=1)# 標準偏差

array([1.63299316, 4.10960934, 2.05480467])

In [132]:
#ユニバーサル関数 numpyの配列を要素ごとに演算を行い、numpy型で返す・

In [136]:
A =np.array([0,1,3,4]).reshape(2,-1)
A

array([[0, 1],
       [3, 4]])

In [138]:
np.sqrt(A)

array([[0.        , 1.        ],
       [1.73205081, 2.        ]])

In [1]:
np.exp(A)

NameError: name 'np' is not defined

In [5]:
import numpy as np
a = np.array([1,2,3])
a*3

array([3, 6, 9])

In [7]:
b = np.array([3,4,3])
np.dot(a,b)

20

In [9]:
np.linspace(0,10,15) # 0-10の区画を15等分

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [17]:
a = np.array([[1,2,3,5], [4,5,6,6],[7,8,8,7]])
a.shape

(3, 4)

In [18]:
a.sum()

62

In [22]:
a.reshape(4,3)
a

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 8, 7]])

In [24]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 8],
       [5, 6, 7]])

In [26]:
np.random.randn(2,3)

array([[-0.28829785,  0.06782629,  0.28400373],
       [-0.25219735,  1.53404958,  0.62215992]])

In [50]:
np.random.randn() # 0-1までの値の中の乱数を返す

-1.2328530855895938

In [52]:
a[1:3, 1:]


array([[5, 6, 6],
       [8, 8, 7]])

In [57]:
a = np.array([[1,2,3],[4,5,6]])
print(type(a))
b = list(a)
print(type(b[0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [62]:
print(a.dtype)

int64


In [64]:
c = a.copy()
c[1] = [10,11,12]

In [68]:
c
print(a)

[[1 2 3]
 [4 5 6]]


In [78]:
a = np.random.randint(10, size=10)
a

array([8, 1, 0, 6, 6, 1, 9, 9, 8, 1])